services:
  moex:
    image: ghcr.io/${GH_USERNAME}/${GH_REPO}:${IMAGE_TAG:-latest}
    pull_policy: always
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AIOGRAM_TOKEN=${AIOGRAM_TOKEN}
      - AIOGRAM_CHAT=${AIOGRAM_CHAT}
      - AIOGRAM_PROXY=${AIOGRAM_PROXY}
      - TINKOFF_TOKEN=${TINKOFF_TOKEN}
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:8.8.0
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
